global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.129.0.39:9100']

  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-red29:8080']
