version: '3'

services:
  app-red29:
    container_name: app-red29
    build: .
    ports:
      - "8029:8080"
    restart: unless-stopped
    logging:
      driver: "json-file"
    networks:
      - demo-network

networks:
  demo-network:
    external: true
